services:
  mongo: 
    image: arm64v8/mongo:4.4.18
    env_file: ".env"
    volumes:
      - mongodata:/data/db
    ports: 
      - 27018:27017
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 30s
      retries: 3
  bot:
    image: bot
    ports: 
      - 8000:8000
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      mongo:
        condition: service_started
    networks:
      - my-network

volumes:
  mongodata:

networks:
  my-network:
    driver: bridge
